export default function activity(
  resource_state,
  athlete,
  name,
  distance,
  moving_time,
  elapsed_time,
  total_elevation_gain,
  type,
  sport_type,
  workout_type,
  activity_id,
  external_id,
  upload_id,
  start_date,
  start_date_local,
  timezone,
  utc_offset,
  start_latlng,
  end_latlng,
  location_city,
  location_state,
  location_country,
  achievement_count,
  kudos_count,
  comment_count,
  athlete_count,
  photo_count,
  map,
  trainer,
  commute,
  manual,
  _private,
  flagged,
  gear_id,
  from_accepted_tag,
  average_speed,
  max_speed,
  average_cadence,
  average_watts,
  weighted_average_watts,
  kilojoules,
  device_watts,
  has_heartrate,
  average_heartrate,
  max_heartrate,
  max_watts,
  pr_count,
  total_photo_count,
  has_kudoed,
  suffer_score
) {
  return {
    getResourceState: () => resource_state,
    getAthlete: () => athlete,
    getName: () => name,
    getDistance: () => distance,
    getMovingTime: () => moving_time,
    getElapsedTime: () => elapsed_time,
    getTotalElevationGain: () => total_elevation_gain,
    getType: () => type,
    getSportType: () => sport_type,
    getWorkoutType: () => workout_type,
    getActivityId: () => activity_id,
    getExternalId: () => external_id,
    getUploadId: () => upload_id,
    getStartDate: () => start_date,
    getStartDateLocal: () => start_date_local,
    getTimezone: () => timezone,
    getUtcOffset: () => utc_offset,
    getStartLatlng: () => start_latlng,
    getEndLatlng: () => end_latlng,
    getLocationCity: () => location_city,
    getLocationState: () => location_state,
    getLocationCountry: () => location_country,
    getAchievementCount: () => achievement_count,
    getKudosCount: () => kudos_count,
    getCommentCount: () => comment_count,
    getAthleteCount: () => athlete_count,
    getPhotoCount: () => photo_count,
    getMap: () => map,
    isTrainer: () => trainer,
    isCommute: () => commute,
    isManual: () => manual,
    isPrivate: () => _private,
    isFlagged: () => flagged,
    getGearId: () => gear_id,
    isFromAcceptedTag: () => from_accepted_tag,
    getAverageSpeed: () => average_speed,
    getMaxSpeed: () => max_speed,
    getAverageCadence: () => average_cadence,
    getAverageWatts: () => average_watts,
    getWeightedAverageWatts: () => weighted_average_watts,
    getKilojoules: () => kilojoules,
    isDeviceWatts: () => device_watts,
    hasHeartrate: () => has_heartrate,
    getAverageHeartrate: () => average_heartrate,
    getMaxHeartrate: () => max_heartrate,
    getMaxWatts: () => max_watts,
    getPrCount: () => pr_count,
    getTotalPhotoCount: () => total_photo_count,
    hasKudoed: () => has_kudoed,
    getSufferScore: () => suffer_score
  };
}
